### ISSUE TITLE
Add client logos to site

### ISSUE THREAD

**Issue by jordanlambrecht** [jordanlambrecht/pb-oct-2022#110]
We need to add all of our client logos to the website. Here's the process:
1. There should be a folder on google drive called 'client logos'. It ha a bunch of PNGs already exported and an illustrator file containing them all. Download that folder.
2. Make sure the client logos in the illustrator file are up to date. If there are any new clients that are missing, ask samee for help tracking them down. Make sure that any new client logos have a transparent background when you place them. Samee can also help you export these when you're ready if you're not sure how.
3. Weed through the client list. We don't need all of them on our site. The purpose of this section is to peacock ourselves by showing off that we have super awesome clients. If you're unsure about one, upload it anyways and we'll sort it out later. Use your best discretion. 
3. Add all the logos we want to use to /public/img/clients
4. Update the json file to make sure the logos get shown. the json file is /data/work-client-list.js. You can hit CMD + P to quick-search for a file.

**Comment by mhahn23** [comment]
Resolves
