### ISSUE TITLE
About Page: Values Descriptions

### ISSUE THREAD

**Issue by oliviaboldt** [jordanlambrecht/pb-oct-2022#73]
For the scroll-over or clickable values on the about page, the body text overlays on top of the buttons. The layout seems a bit wonky on desktop.
<img width="1414" alt="Screen Shot 2022-01-03 at 2 41 00 PM (2)" src="https://user-images.githubusercontent.com/94932415/147978204-8e3776e4-2441-4417-ab44-b15ad66d9366.png">

**Comment by jordanlambrecht** [comment]
Repeat issue, see #13
